### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by poly000** [poly000/waylyrics#1]
- [ ] auto Always on top with wayland - blocked by https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/44
- [x] Custom font support (font-family in style.css)
- [x] #17
    - [x] netease
    - [ ] QQ music
    - [ ] kgmusic
    - [ ] kwmusic
    - [ ] mgmusic
- [x] match lyric by length info
- [x] logging by @taoky 
- [x] do not panic on unsupported player, give error information instead.
- [x] #8
- [x] Lyrics cache
    - [x] #13
- [ ] #9
- [ ] #10

**Comment by poly000** [comment]
Iterator<'a, Item=(&'a str, Time)>
